#!/bin/bash
# testing closing file descriptors
exec 3> test17file
echo "This is a test line of data" >&3
#close file descriptors
exec 3>&-
#then it can not input file descriptors
echo "This won't work" >&3


